### ISSUE TITLE
wget

### ISSUE THREAD

**Issue by mrezentes** [jrezentes/Learning#13]
https://www.youtube.com/watch?v=4SBkwNx1WkA

**Comment by jrezentes** [comment]
@mrezentes seems to me like there is too much power in this command. Takeaway tip: Use this in legal, moral ways. (Awesome that you can download in the backround so you can still use terminal.)

**Comment by mrezentes** [comment]
@jrezentes Please expand on how this can be used illegally or immorally.
Remember, if you are making something you have to assume that there is
someone waiting to abuse it.

**Comment by jrezentes** [comment]
@mrezentes Well He explains how you can download mp3 using URL lists in .txt files for 1. Secondly, spoofing may allow for you to access certain site privileges that requires payment before accessing, such as the example he uses with hulu(when he explained how to spoof a user agent.).

**Comment by mrezentes** [comment]
To protect against such abuse, headers can be added to files in the server.
Like using the access origin header. You should take a quick look at how
that one works
